# ============ 生成题目详情页 ============
. (Join-Path $PSScriptRoot 'kb_common.ps1')

Write-Host 'generating detail pages...'
$idx = 0
foreach ($t in $topicSeq) {
    $idx++
    $d = $details[$t.key]
    if (-not $d) { Write-Host "no detail for $($t.key)"; continue }

    $lv = 0
    if ($d.level) { $lv = [double]$d.level }
    $lvStr = Get-LevelStr $lv
    $lvLabel = Get-LevelLabel $lv
    $cat = if ($d.category) { $d.category } else { '' }

    # 分类标签 chips
    $chipArr = New-Object System.Collections.ArrayList
    [void]$chipArr.Add("<span class=""chip chip-cat"">$cat</span>")
    [void]$chipArr.Add("<span class=""chip chip-diff"">$lvStr $lvLabel</span>")
    foreach ($tg in $t.tags) {
        [void]$chipArr.Add("<a class=""chip chip-tag"" href=""../categories/$tg.html"">$tg</a>")
    }
    $chips = $chipArr -join "`n"

    # 面包屑（取第一个分类）
    $crumbCat = if ($t.tags.Count -gt 0) { $t.tags[0] } else { '' }
    $crumbHtml = "<a href=""../index.html"">首页</a><span>/</span>"
    if ($crumbCat) { $crumbHtml += "<a href=""../categories/$crumbCat.html"">$crumbCat</a><span>/</span>" }
    $crumbHtml += "<span class=""now"">第 $($t.n) 题</span>"

    # 内容渲染
    $descHtml = Convert-Markdown $d.desc
    $expHtml = Convert-Markdown $d.explanation
    $pivotHtml = ''
    if ($d.pivot) { $pivotHtml = "<section class=""q-pivot""><b>要点</b>：$(Convert-Markdown $d.pivot)</section>" }
    # 选择题选项
    $optionsHtml = ''
    if ($d.options) {
        try {
            $opt = $null
            if ($d.options -is [string]) { $opt = $d.options | ConvertFrom-Json } else { $opt = $d.options }
            if ($opt -and $opt.options) {
                $labels = @('A','B','C','D','E','F','G','H')
                $ansIdx = @()
                if ($opt.answer) { $ansIdx = @($opt.answer) }
                $optArr = New-Object System.Collections.ArrayList
                $oi = 0
                foreach ($oc in $opt.options) {
                    $label = if ($oi -lt $labels.Count) { $labels[$oi] } else { ($oi + 1) }
                    $isAns = $ansIdx -contains $oi
                    $cls = if ($isAns) { 'opt opt-ans' } else { 'opt' }
                    $mark = if ($isAns) { '<span class="opt-mark">&#10003;</span>' } else { '' }
                    [void]$optArr.Add("<div class=""$cls""><span class=""opt-label"">$label</span><span class=""opt-text"">$(Convert-Inline ([string]$oc))</span>$mark</div>")
                    $oi++
                }
                $optionsHtml = '<div class="q-options">' + ($optArr -join '') + '</div>'
            }
        } catch { }
    }

    # 上一题/下一题
    $prevHtml = ''
    $nextHtml = ''
    if ($idx -gt 1) {
        $prev = $topicSeq[$idx - 2]
        $prevHtml = "<a class=""prev"" href=""$($prev.n).html""><span class=""dir"">← 上一题</span><span class=""tt"">$($prev.title)</span></a>"
    }
    if ($idx -lt $total) {
        $next = $topicSeq[$idx]
        $nextHtml = "<a class=""next"" href=""$($next.n).html""><span class=""dir"">下一题 →</span><span class=""tt"">$($next.title)</span></a>"
    }

    $descBlock = ''
    if ($descHtml -or $optionsHtml) {
        $descBlock = @"
    <section class="q-block">
      <h2 class="q-block-title">题目</h2>
      <div class="q-block-body">$descHtml$optionsHtml</div>
    </section>
"@
    }

    $html = @"
<!-- Generated by Trae Work -->
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>第 $($t.n) 题：$($t.title) - 前端面试题知识库</title>
<link rel="stylesheet" href="../assets/style.css">
</head>
<body>
<header class="topbar"><div class="wrap topbar-inner">
  <a class="brand" href="../index.html">前端面试题<em>知识库</em></a>
  <nav class="crumbs">$crumbHtml</nav>
</div></header>
<main class="wrap">
  <article class="q-detail">
    <div class="q-meta">
$chips
    </div>
    <h1 class="q-title">$($t.title)</h1>
    $descBlock
    <section class="q-block q-block-answer">
      <h2 class="q-block-title">参考答案</h2>
      <div class="q-block-body">$expHtml</div>
    </section>
    $pivotHtml
  </article>
  <nav class="q-nav">$prevHtml$nextHtml</nav>
</main>
$(Get-FooterHtml)
<script src="../assets/site.js"></script>
</body>
</html>
"@
    Write-Utf8 "$qDir\$($t.n).html" $html
    if (($idx % 200) -eq 0) { Write-Host "progress $idx/$total" }
}
Write-Host "DETAIL PAGES DONE: $total"
